service: autoping-lambda-bot-tele

frameworkVersion: '3'
variablesResolutionMode: 20210326

custom:
  secret: ${ssm:/aws/reference/secretsmanager/dev/autoping/telebot}

provider:
  name: aws
  stage: dev
  region: eu-central-1
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  environment:
    TOKEN: ${self:custom.secret.token}

functions:

  receiveMessage:
    handler: handler.receiveMessage
    events:
      - http:
          path: messages/inbound
          method: post
          async: true

  sendMessage:
    handler: handler.sendMessage
    events:
      - http:
          path: messages/outbound
          method: post
          async: true

resources:
  Resources:
    inbound:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: sqs-queue-autoping-inbound
        FifoQueue: true
    outbound:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: sqs-queue-autoping-outbound
        FifoQueue: true

plugins:
  - serverless-ignore
  - serverless-offline
