service: autoping-lambda-bot-tele

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  region: eu-central-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  sendMessage:
    handler: index.sendMessage
    events:
      - http:
          path: messages
          method: post
          cors: true

plugins:
  - serverless-ignore
  - serverless-offline
